* added removal of the oldest AMI - when there are more then 2 AMIs only
* checking if there is AMI removal process, so then lambdas must be updated - with the newest AMI

* updating Lambdas is multitasking - 8x faster then linear

diff --git a/config_aws b/config_aws
--- a/config_aws
+++ b/config_aws
@@ -299,11 +299,10 @@ aws_newest_ami()
 {
   if [ -s "${TMP}/${AWS_AMIS_DETAILS}_full.json" ]
   then
-    inf "Trying to figure it out the newest AMI:"
     AWS_AMI_IMAGE_AMOUNT=$(jq -r '.Images[].ImageId' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | wc -l)
     LATEST_AMI_ID=$(jq -r '.Images[] | .CreationDate + " " + .ImageId' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | sort | tail -n1 | awk '{print $2}')
     OLDEST_AMI_ID=$(jq -r '.Images[] | .CreationDate + " " + .ImageId' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | sort | head -n1 | awk '{print $2}')
-    inf "  The latest one seems to be this one: ${BROWN}${LATEST_AMI_ID}"
+    inf "  The latest AMI seems to be this one: ${BROWN}${LATEST_AMI_ID}"
     IMAGE_STATE=$(jq -r --arg ImageId ${LATEST_AMI_ID} '.Images[] | select(.ImageId == $ImageId) | .State' "${TMP}/${AWS_AMIS_DETAILS}_full.json")
     if [[ ${IMAGE_STATE} == "available" ]]
     then
@@ -331,9 +330,13 @@ aws_newest_ami()
     if [ ${AWS_AMI_IMAGE_AMOUNT} -ge 3 ]
     then
       debug "      And the oldest seems to be this one: ${BROWN}${OLDEST_AMI_ID}${BLUE}, among: ${BROWN}${AWS_AMI_IMAGE_AMOUNT}"
-      if [[ ${CLEANING} == yes ]] && [[ ${XTRA_CLEANING} == yes ]]
+      export AMI_TOBE_REMOVED=${OLDEST_AMI_ID}
+      if [[ ${CLEANING} == yes ]] #&& [[ ${XTRA_CLEANING} == yes ]]
       then
+        warn "        ${BROWN}${OLDEST_AMI_ID}${WINE} will be deregistered now..."
         aws ${AWS_PROFILE_USE_CHECK[*]} ec2 deregister-image --image-id ${OLDEST_AMI_ID} > "${TMP}/${AWS_AMIS_DETAILS}_${OLDEST_AMI_ID}_rm.json" 2> "${LOG}/${AWS_AMIS_DETAILS}_${OLDEST_AMI_ID}_rm.log"
+        ERROR_CODE="$?"
+        #ToDo: deregisteering AMI move to function
       fi
     fi
   else
@@ -1005,10 +1008,98 @@ lambda_function_deployment()
       done
       inf "    Lambda function: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}${CYAN} deployed properly"
       EC2_LAMBDA_SCRIPT_ARN=$(jq -r '.FunctionArn' "${TMP}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_full.json")
-      debug "      Slack notification...."
+      if [[ ${VERBOSE} == yes ]]
+      then
+        debug "      Slack notification...."
+      fi
       source "${SCRIPTS_HOME}/slack_notification_lambda"
     fi
   fi
+}
+
+lambda_function_update()
+{
+  if [ $# -ne 1 ]
+  then
+    error "Function ${LIME}${FUNCNAME[0]}${RED} needs one parameter: ${YELLOW}(1)lambda_name"
+    ERROR_CODE="1"
+    failed
+  else
+    AWS_LAMBDA_FUNCTION_NAME="${1}"
+  fi
+  inf "Preparing Lambda function update: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}"
+  IFS=${NEWIFS}
+  for LAMBDA_SCRIPT_LINE in $(grep -v "^#" "${SCRIPTS_HOME}/lambda_functions/lambda_events.config")
+  do
+    LAMBDA_SCRIPT=$(echo "${LAMBDA_SCRIPT_LINE}" | awk -F\~ '{print $1}')
+    LAMBDA_SCRIPT_NAME=$(echo ${LAMBDA_SCRIPT} | awk -F\. '{print $1}')
+    SHELL_SCRIPT=$(echo "${LAMBDA_SCRIPT_LINE}" | awk -F\~ '{print $2}')
+    SHELL_SCRIPT_NAME=$(echo ${SHELL_SCRIPT} | awk -F\. '{print $1}')
+    SHELL_SCRIPT_CONTENT=$(cat "${SCRIPTS_HOME}/lambda_functions/${SHELL_SCRIPT}")
+    RANDOM_ID_GEN=$(head -n10 /dev/urandom | tr -dc '0-9a-zA-Z' | fold -w 4 | head -n1)
+    AWS_LAMBDA_NAME="${AWS_COMMON_NAME}_${SHELL_SCRIPT_NAME}_${LAMBDA_SCRIPT_NAME}"
+    AWS_HANDLER_FUNCTION_NAME="${LAMBDA_SCRIPT_NAME}_handler"
+    AWS_LAMBDA_HANDLER="${AWS_LAMBDA_NAME}.${AWS_HANDLER_FUNCTION_NAME}"
+    if [[ ${AWS_LAMBDA_NAME} == "${AWS_LAMBDA_FUNCTION_NAME}" ]]
+    then    
+      export SHELL_SCRIPT_CONTENT
+      export KEY_NAME
+      export AWS_EC2_INSTANCES_PROFILE
+      export AWS_HANDLER_FUNCTION_NAME
+      export AWS_AMI_ID
+      export AWS_INSTANCE_TYPE
+      export SUBNET_ID
+      export REGION
+      export SECURITY_GROUP_ID
+      cat "${SCRIPTS_HOME}/lambda_functions/${LAMBDA_SCRIPT}" | envsubst > "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.py"
+      if [[ ${ZIP_ON} == yes ]]
+      then
+        zip -j -q "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.zip" "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.py"
+      elif [[ ${SP_ON} == yes ]]
+      then
+        7z a "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.zip" "${SCRIPTS_HOME}/${AWS_LAMBDA_FUNCTION_NAME}.py" > "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}_compress.output" 2>"${LOG}/${AWS_LAMBDA_FUNCTION_NAME}_compress.log"
+      fi
+      NUMBER=0
+      while [ ${NUMBER} -le 10 ]
+      do
+        sleep 1
+        #ProgressBar ${NUMBER} 10
+        NUMBER=$(( ${NUMBER} + 1))
+      done
+      printf '\n'
+      inf "  Updating Lambda function: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}"
+      aws ${AWS_PROFILE_USE_CHECK[*]} lambda update-function-code --function-name ${AWS_LAMBDA_FUNCTION_NAME} --zip-file fileb://"${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.zip" > "${TMP}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_update_full.json" 2>"${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_update.log"
+      ERROR_CODE="$?"
+      if [ ${ERROR_CODE} -ne 0 ]
+      then
+        error "    Lambda function: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}${RED} cannot be updated"
+        debug "      LOG FILE: ${YELLOW}${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_update.log"
+        ENCODED_ERROR_MESSAGE=$(grep "\[ERROR\]" "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_update.log" | awk -F"failure message:" '{print $2}')
+        DECODED_ERROR_MESSAGE=$(aws ${AWS_PROFILE_USE_CHECK[*]} sts decode-authorization-message --output text --encoded-message ${ENCODED_ERROR_MESSAGE} | jq -r)
+        error "        ${DECODED_ERROR_MESSAGE}"
+        failed
+      else
+        while [[ $(aws ${AWS_PROFILE_USE_CHECK[*]} lambda get-function --function-name ${AWS_LAMBDA_FUNCTION_NAME} | jq -r '.Configuration.State') == "Pending" ]]
+        do
+          for NUMBER in {1..100}
+          do
+            sleep 0.15
+            aws ${AWS_PROFILE_USE_CHECK[*]} lambda get-function --function-name ${AWS_LAMBDA_FUNCTION_NAME} | jq -r '.Configuration.State'
+            #ProgressBar ${NUMBER} 100
+          done
+          printf '\n'
+        done
+        inf "    Lambda function: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}${CYAN} updated properly"
+        EC2_LAMBDA_SCRIPT_ARN=$(jq -r '.FunctionArn' "${TMP}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_update_full.json")
+        if [[ ${VERBOSE} == yes ]]
+        then
+          debug "      Slack notification...."
+        fi
+        slack_notification ${SLACK_CHANNEL_AWS} "AWS Lambda function notification" "AWS Lambda function: *${AWS_LAMBDA_FUNCTION_NAME}* has been updated" ":musical_score:" "good" "${AWS_LOGIN_URL}" "AWS log in:"
+      fi
+    fi
+  done
+  IFS=${ORIGIFS}
 }
 
 aws_list-entities-for-policy()
@@ -1832,7 +1923,10 @@ events_create_cron_rule()
     if [ ${ERROR_CODE} -eq 0 ]
     then
       inf "      Event rule: ${LIME}${EVENT_BRIDGE_RULE_NAME}${CYAN} added properly"
-      debug "        Slack notification...."
+      if [[ ${VERBOSE} == yes ]]
+      then
+        debug "      Slack notification...."
+      fi
       source "${SCRIPTS_HOME}/slack_notification_event_rule"
     else
       error "      Event rule: ${LIME}${EVENT_BRIDGE_RULE_NAME}${RED} failed to add"
@@ -1958,7 +2052,10 @@ events_add_target_to_rule()
     if [ ${ERROR_CODE} -eq 0 ]
     then
       inf "        Target: ${GREEN}${EVENT_BRIDGE_TARGET_ID}${CYAN} added properly"
-      debug "          Slack notification...."
+      if [[ ${VERBOSE} == yes ]]
+      then
+        debug "      Slack notification...."
+      fi
       source "${SCRIPTS_HOME}/slack_notification_lambda_target"
     else
       error "        Target: ${GREEN}${EVENT_BRIDGE_TARGET_ID}${RED} wasn't added"
