* added creating and checking customer managed KMS key
* based on this key AMI is checked, and if existing AMI is not encrypted with customer key - then it is copied to be shared

* a bit of cleaning

diff --git a/config_aws b/config_aws
--- a/config_aws
+++ b/config_aws
@@ -135,16 +135,30 @@ log_tmp_maintenance()
         warn "    ${BROWN}${BACKUP_OUTPUT_FILE}${WINE} - AWS S3 bucket is not provided, so default one is choosen: ${YELLOW}${S3_BUCKET_NAME}"
         inf "    Copying ${BROWN}${BACKUP_OUTPUT_FILE}${CYAN} to AWS S3 bucket: ${YELLOW}${S3_BUCKET_NAME}"
         aws ${AWS_PROFILE_USE_CHECK[*]} s3 cp "${VAR}/${BACKUP_OUTPUT_FILE}" s3://${S3_BUCKET_NAME}/ --storage-class STANDARD_IA > "${VAR}/S3_copying_log_tmp.log" 2>&1
-        #aws ${AWS_PROFILE_USE_CHECK[*]} s3 presign "s3://${S3_BUCKET_NAME}/${BACKUP_OUTPUT_FILE}" --expires-in ...
       else
         inf "    Copying ${BROWN}${BACKUP_OUTPUT_FILE}${CYAN} to AWS S3 bucket: ${YELLOW}${S3_BUCKET_NAME}"
         aws ${AWS_PROFILE_USE_CHECK[*]} s3 cp "${VAR}/${BACKUP_OUTPUT_FILE}" s3://${S3_BUCKET_NAME}/ --storage-class STANDARD_IA > "${VAR}/S3_copying_log_tmp.log" 2>&1
-        #aws ${AWS_PROFILE_USE_CHECK[*]} s3 presign "s3://${S3_BUCKET_NAME}/${BACKUP_OUTPUT_FILE}" --expires-in ...
       fi
     fi
   else
     inf "  I couldn't archive tmp and log files"
   fi
+}
+
+link_presign_s3_file()
+{
+  if [ $# -ne 3 ]
+  then
+    error "Function ${LIME}${FUNCNAME[0]}${RED} needs three parameters: ${YELLOW}(1)s3 bucket name, (2)name of the file, (3)expires[s]"
+    ERROR_CODE="1"
+    failed
+  else
+    S3_BUCKET_NAME="${1}"
+    NAME_OF_FILE_STORED=${2}
+    EXPIRE_TIME="${3}"
+  fi
+  #"${SCRIPT_NAME}_${CURRENT_TIMESTAMP}.tar.xz"
+  export PRESIGNED_LINK=$(aws ${AWS_PROFILE_USE_CHECK[*]} s3 presign "s3://${S3_BUCKET_NAME}/${NAME_OF_FILE_STORED}" --expires-in ${EXPIRE_TIME})
 }
 
 slack_vm_start()
@@ -198,6 +212,7 @@ aws_connectivity_check()
     export AWS_OWNER_ID=$(jq -r '.Account' "${TMP}/${AWS_ACCOUNT}_full.json")
     export AWS_USER_ID=$(jq -r '.UserId' "${TMP}/${AWS_ACCOUNT}_full.json")
     export AWS_ARN_USER=$(jq -r '.Arn' "${TMP}/${AWS_ACCOUNT}_full.json")
+    export AWS_REGION=$(aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-availability-zones --output text --query 'AvailabilityZones[0].[RegionName]')
     if [[ ${VERBOSE} == yes ]]
     then
       debug "ownerId: ${WINE}${AWS_OWNER_ID}"
@@ -223,8 +238,8 @@ aws_default_subnet()
       debug "  taking randomly ANY subnet"
       SUBNET_ID=$(shuf -e $(jq -r '.Subnets[] | .SubnetId' "${TMP}/${AWS_SUBNETS_DETAILS}_full.json") | tail -n1)
     fi
-    AVAILABILITY_ZONE=$(jq -r --arg subnet_id ${SUBNET_ID} '.Subnets[] | select(.SubnetId == $subnet_id) | .AvailabilityZone' "${TMP}/${AWS_SUBNETS_DETAILS}_full.json")
-    REGION=$(aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-availability-zones | jq -r --arg availability_zone ${AVAILABILITY_ZONE} '.AvailabilityZones[] | select(.ZoneName == $availability_zone) | .RegionName')
+    export AVAILABILITY_ZONE=$(jq -r --arg subnet_id ${SUBNET_ID} '.Subnets[] | select(.SubnetId == $subnet_id) | .AvailabilityZone' "${TMP}/${AWS_SUBNETS_DETAILS}_full.json")
+    #export AWS_REGION=$(aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-availability-zones | jq -r --arg availability_zone ${AVAILABILITY_ZONE} '.AvailabilityZones[] | select(.ZoneName == $availability_zone) | .RegionName')
   else
     error "  There is no AWS Networks... exiting"
     failed
@@ -313,7 +328,6 @@ aws_newest_ami()
 {
   if [ -s "${TMP}/${AWS_AMIS_DETAILS}_full.json" ]
   then
-    #AWS_AMI_IMAGE_AMOUNT=$(jq -r '.Images[].ImageId' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | wc -l)
     AWS_AMI_IMAGE_AMOUNT=$(jq -r '.Images[] | .CreationDate + " " + .ImageId + " " + .Name' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | grep "kpn_" | wc -l)
     LATEST_AMI_ID=$(jq -r '.Images[] | .CreationDate + " " + .ImageId + " " + .Name' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | grep "kpn_" | sort | tail -n1 | awk '{print $2}')
     OLDEST_AMI_ID=$(jq -r '.Images[] | .CreationDate + " " + .ImageId + " " + .Name' "${TMP}/${AWS_AMIS_DETAILS}_full.json" | grep "kpn_" | sort | head -n1 | awk '{print $2}')
@@ -332,7 +346,7 @@ aws_newest_ami()
     elif [[ ${IMAGE_STATE} == "pending"  ]]
     then
       warn "    Image: ${BROWN}${LATEST_AMI_ID}${WINE} is in status ${ORANGE}pending${WINE}, waiting for state change"
-      while [[ $(aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-images ${AWS_PROFILE_USE_CHECK[*]} --image-ids  ${LATEST_AMI_ID} | jq -r '.Images[].State') == "available" ]]
+      while [[ $(aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-images --image-ids  ${DESTINATION_AMI_ID} | jq -r '.Images[].State') == "pending" ]]
       do
         for NUMBER in {1..100}
         do
@@ -347,7 +361,7 @@ aws_newest_ami()
     then
       debug "      And the oldest seems to be this one: ${BROWN}${OLDEST_AMI_ID}${BLUE}, among: ${BROWN}${AWS_AMI_IMAGE_AMOUNT}"
       export AMI_TOBE_REMOVED=${OLDEST_AMI_ID}
-      if [[ ${CLEANING} == yes ]] #&& [[ ${XTRA_CLEANING} == yes ]]
+      if [[ ${CLEANING} == yes ]]
       then
         warn "        ${BROWN}${OLDEST_AMI_ID}${WINE} will be deregistered now..."
         aws ${AWS_PROFILE_USE_CHECK[*]} ec2 deregister-image --image-id ${OLDEST_AMI_ID} > "${TMP}/${AWS_AMIS_DETAILS}_${OLDEST_AMI_ID}_rm.json" 2> "${LOG}/${AWS_AMIS_DETAILS}_${OLDEST_AMI_ID}_rm.log"
@@ -544,6 +558,113 @@ aws_list-securitygroups()
     error "      $(cat "${LOG}/${AWS_SECURITY_GROUPS}.log")"
     failed
   fi
+}
+
+aws_KMS_customer_key_create()
+{
+  inf "${MAGENTA}Creating KMS customer key for snapshot/AMI encription"
+  if [[ ${AWS_OWNER_ID} == "623623120519" ]]
+  then
+    SECOND_AWS_OWNER_ID="365117780834"
+  elif [[ ${AWS_OWNER_ID} == "365117780834" ]]
+  then
+    SECOND_AWS_OWNER_ID="623623120519"
+  fi
+  AWS_AMI_CUSTOMER_KEY_ALIAS="alias/key-share-${AWS_OWNER_ID}-and-${SECOND_AWS_OWNER_ID}"
+  AWS_POLICY_NAME="key-share-policy-${AWS_OWNER_ID}-and-${SECOND_AWS_OWNER_ID}"
+  if [ -s "${TMP}/${AWS_KMS_ALIASES}_full.json" ]
+  then
+    export AWS_KMS_CUSTOM_KEY_ID=$(jq -r --arg alias_name "${AWS_AMI_CUSTOMER_KEY_ALIAS}" '.Aliases[] | select(.AliasName == $alias_name) | .TargetKeyId' "${TMP}/${AWS_KMS_ALIASES}_full.json")
+    if [ -z ${AWS_KMS_CUSTOM_KEY_ID} ] || [[ ${AWS_KMS_CUSTOM_KEY_ID} == null ]]
+    then
+      echo "{
+              \"Id\": \"key-custom-${AWS_OWNER_ID}-and-${SECOND_AWS_OWNER_ID}\",
+              \"Version\": \"2012-10-17\",
+              \"Statement\": 
+              [
+                {
+                  \"Sid\": \"Enable IAM User Permissions\",
+                  \"Effect\": \"Allow\",
+                  \"Principal\": 
+                  {
+                    \"AWS\": \"arn:aws:iam::${AWS_OWNER_ID}:root\"
+                    },
+                  \"Action\": \"kms:*\",
+                  \"Resource\": \"*\"
+                  },
+                {
+                  \"Sid\": \"Allow use of the key\",
+                  \"Effect\": \"Allow\",
+                  \"Principal\": 
+                  {
+                    \"AWS\": 
+                    [
+                      \"arn:aws:iam::${AWS_OWNER_ID}:role/${AWS_LAMBDA_ROLE}\",
+                      \"arn:aws:iam::${AWS_OWNER_ID}:role/${AWS_EC2_ROLE}\",
+                      \"arn:aws:iam::${SECOND_AWS_OWNER_ID}:root\"
+                      ]
+                    },
+                  \"Action\": 
+                  [
+                    \"kms:Encrypt\",
+                    \"kms:Decrypt\",
+                    \"kms:ReEncrypt*\",
+                    \"kms:GenerateDataKey*\",
+                    \"kms:DescribeKey\"
+                    ],
+                  \"Resource\": \"*\"
+                  },
+                {
+                  \"Sid\": \"Allow attachment of persistent resources\",
+                  \"Effect\": \"Allow\",
+                  \"Principal\": 
+                  {
+                    \"AWS\": 
+                    [
+                      \"arn:aws:iam::${AWS_OWNER_ID}:role/${AWS_LAMBDA_ROLE}\",
+                      \"arn:aws:iam::${AWS_OWNER_ID}:role/${AWS_EC2_ROLE}\",
+                      \"arn:aws:iam::${SECOND_AWS_OWNER_ID}:root\"
+                      ]
+                    },
+                  \"Action\": 
+                  [
+                    \"kms:CreateGrant\",
+                    \"kms:ListGrants\",
+                    \"kms:RevokeGrant\"
+                    ],
+                  \"Resource\": \"*\",
+                  \"Condition\": 
+                  {
+                    \"Bool\": 
+                    {
+                      \"kms:GrantIsForAWSResource\": \"true\"
+                      }
+                    }
+                  }
+                ]
+              }" > "${TMP}/${AWS_POLICIES}_${AWS_POLICY_NAME}-def.json"
+      aws ${AWS_PROFILE_USE_CHECK[*]} kms create-key --description "Teradata team key which will be used to encrypt snapshot/AMI shared to ${SECOND_AWS_OWNER_ID} account (from ${AWS_OWNER_ID})" --key-usage ENCRYPT_DECRYPT --key-spec SYMMETRIC_DEFAULT --policy file://"${TMP}/${AWS_POLICIES}_${AWS_POLICY_NAME}-def.json" > "${TMP}/${AWS_KMS_ALIASES}_share_customer_key_full.json" 2> "${LOG}/${AWS_KMS_ALIASES}_share_customer_key.log"
+      aws ${AWS_PROFILE_USE_CHECK[*]} kms describe-key --key-id ${AWS_KMS_CUSTOM_KEY_ID} > "${TMP}/${AWS_KMS_ALIASES}_${AWS_KMS_CUSTOM_KEY_ID}_full.json" 2>"${LOG}/${AWS_KMS_ALIASES}_${AWS_KMS_CUSTOM_KEY_ID}.log"
+      if [ -s "${TMP}/${AWS_KMS_ALIASES}_share_customer_key_full.json" ]
+      then
+        NEW_CUSTOM_KEY_ID=$(jq -r '.KeyMetadata.KeyId' "${TMP}/${AWS_KMS_ALIASES}_share_customer_key_full.json")
+        aws ${AWS_PROFILE_USE_CHECK[*]} kms create-alias --alias-name "alias/key-share-${AWS_OWNER_ID}-and-${SECOND_AWS_OWNER_ID}" --target-key-id "${NEW_CUSTOM_KEY_ID}" "${TMP}/${AWS_KMS_ALIASES}_${NEW_CUSTOM_KEY_ID}_full.json" 2> "${LOG}/${AWS_KMS_ALIASES}_${NEW_CUSTOM_KEY_ID}.log"
+      fi
+    else
+      inf "  KMS custom KeyID: ${LIGHT_BLUE}${AWS_KMS_CUSTOM_KEY_ID}${CYAN}, with an KeyAlias: ${BROWN}${AWS_AMI_CUSTOMER_KEY_ALIAS}${CYAN} exists"
+      aws ${AWS_PROFILE_USE_CHECK[*]} kms describe-key --key-id ${AWS_KMS_CUSTOM_KEY_ID} > "${TMP}/${AWS_KMS_ALIASES}_${AWS_KMS_CUSTOM_KEY_ID}_full.json" 2>"${LOG}/${AWS_KMS_ALIASES}_${AWS_KMS_CUSTOM_KEY_ID}.log"
+      AWS_KMS_CUSTOM_KEY_ID_ENABLED=$(jq -r '.KeyMetadata.Enabled' "${TMP}/${AWS_KMS_ALIASES}_${AWS_KMS_CUSTOM_KEY_ID}_full.json")
+      if [[ ${AWS_KMS_CUSTOM_KEY_ID_ENABLED} == true ]]
+      then
+        inf "    and it is ${GREEN}enabled"
+      fi
+    fi
+  fi
+}
+
+aws_KMS_customer_key_delete()
+{
+aws ${AWS_PROFILE_USE_CHECK[*]} kms schedule-key-deletion --key-id ${} --pending-window-in-days 7
 }
 
 aws_AMI_create()
@@ -1014,16 +1135,12 @@ lambda_function_deployment()
       error "        ${DECODED_ERROR_MESSAGE}"
       failed
     else
-      while [[ $(aws ${AWS_PROFILE_USE_CHECK[*]} lambda get-function --function-name ${AWS_LAMBDA_FUNCTION_NAME} | jq -r '.Configuration.State') == "Pending" ]]
-      do
         for NUMBER in {1..100}
         do
-          sleep 0.15
-          aws ${AWS_PROFILE_USE_CHECK[*]} lambda get-function --function-name ${AWS_LAMBDA_FUNCTION_NAME} | jq -r '.Configuration.State'
+          sleep 0.03
           ProgressBar ${NUMBER} 100
         done
         printf '\n'
-      done
       inf "    Lambda function: ${YELLOW}${AWS_LAMBDA_FUNCTION_NAME}${CYAN} deployed properly"
       EC2_LAMBDA_SCRIPT_ARN=$(jq -r '.FunctionArn' "${TMP}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_FUNCTION_NAME}_full.json")
       if [[ ${VERBOSE} == yes ]]
@@ -1067,7 +1184,7 @@ lambda_function_update()
       export AWS_AMI_ID
       export AWS_INSTANCE_TYPE
       export SUBNET_ID
-      export REGION
+      export AWS_REGION
       export SECURITY_GROUP_ID
       cat "${SCRIPTS_HOME}/lambda_functions/${LAMBDA_SCRIPT}" | envsubst > "${TMP}/${AWS_LAMBDA_FUNCTION_NAME}.py"
       if [[ ${ZIP_ON} == yes ]]
@@ -1081,7 +1198,6 @@ lambda_function_update()
       while [ ${NUMBER} -le 10 ]
       do
         sleep 1
-        #ProgressBar ${NUMBER} 10
         NUMBER=$(( ${NUMBER} + 1))
       done
       printf '\n'
@@ -1846,13 +1962,43 @@ if [ $# -ne 1 ]
     SECURITY_GROUP_ID="${1}"
   fi
   inf "    Deleting security group ${YELLOW}${SECURITY_GROUP_ID}"
-  aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-network-interfaces --filters Name=group-id,Values=${SECURITY_GROUP_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" 2>&1 
-  if [ ! -z $(jq -r '.NetworkInterfaces[].Attachment.InstanceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" | head -n1) ]
+  aws ${AWS_PROFILE_USE_CHECK[*]} ec2 describe-network-interfaces --filters Name=group-id,Values=${SECURITY_GROUP_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" 2>"${LOG}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}.log" 
+  if [ ! -z $(jq -r '.NetworkInterfaces[].Attachment.InstanceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" | head -n1) ] && [[ $(jq -r '.NetworkInterfaces[].Attachment.InstanceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" | head -n1) != null ]]
   then
     for INSTANCE_ID in $(jq -r '.NetworkInterfaces[].Attachment.InstanceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json")
     do
       warn "      Security group: ${BROWN}${SECURITY_GROUP_ID}${WINE} is still attached to InstanceId: ${YELLOW}${INSTANCE_ID}"
     done
+  elif [ ! -z $(jq -r '.NetworkInterfaces[].NetworkInterfaceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" | head -n1) ]
+  then
+    inf "      Security group ${YELLOW}${SECURITY_GROUP_ID}${CYAN} has attached interfaces... removing them first"
+    for INTERFACE_ID in $(jq -r '.NetworkInterfaces[].NetworkInterfaceId' "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json")
+    do
+      inf "        Removing interfaceId: ${BROWN}${INTERFACE_ID}"
+      aws ${AWS_PROFILE_USE_CHECK[*]}  ec2 delete-network-interface --network-interface-id ${INTERFACE_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_removal.json" 2> "${LOG}/${AWS_SECURITY_GROUPS}_network_interface_${INTERFACE_ID}_removal.log"
+      ERROR_CODE="$?"
+      if [ ${ERROR_CODE} -eq 0 ]
+      then
+        inf "          InterfaceId: ${BROWN}${INTERFACE_ID}${CYAN} removed properly"
+      else
+        error "          InterfaceId: ${BROWN}${INTERFACE_ID}${RED} couldn't be removed"
+        debug "            LOG_FILE: ${YELLOW}${LOG}/${AWS_SECURITY_GROUPS}_network_interface_${INTERFACE_ID}_removal.log"
+        failed
+      fi
+    done
+    aws ${AWS_PROFILE_USE_CHECK[*]} ec2 delete-security-group --group-id ${SECURITY_GROUP_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_delete_security_group.json"  2>&1
+    ERROR_CODE="$?"
+    if [ ${ERROR_CODE} -eq 0 ]
+    then
+      inf "      Security group: ${BROWN}${SECURITY_GROUP_ID}${CYAN} has been deleted properly"
+    elif grep -q "cannot be deleted by a user" "${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_delete_security_group.json"
+    then
+      warn "      Security group: ${BROWN}${SECURITY_GROUP_ID}${RED} cannot be deleted by the user"
+    else
+      error "      Security group: ${BROWN}${SECURITY_GROUP_ID}${RED} deletion failed, exiting"
+      debug "        LOG FILE: ${YELLOW}${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_delete_security_group.json"
+      failed
+    fi
   else
     aws ${AWS_PROFILE_USE_CHECK[*]} ec2 delete-security-group --group-id ${SECURITY_GROUP_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_delete_security_group.json"  2>&1
     ERROR_CODE="$?"
@@ -1956,7 +2102,7 @@ event_bridge_remove_target()
     EVENT_BRIDGE_TARGET_ID="${1}"
     EVENT_BRIDGE_RULE_NAME="${2}"
   fi
-  inf "        Target: ${GREEN}${EVENT_BRIDGE_TARGET_ID}${CYAN} will be removed from rule:  ${LIME}${EVENT_BRIDGE_RULE_NAME}"
+  inf "        Target: ${GREEN}${EVENT_BRIDGE_TARGET_ID}${CYAN} will be removed from rule: ${LIME}${EVENT_BRIDGE_RULE_NAME}"
   aws ${AWS_PROFILE_USE_CHECK[*]} events remove-targets --rule ${EVENT_BRIDGE_RULE_NAME} --ids ${EVENT_BRIDGE_TARGET_ID} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}_target_removal_full.json" 2>&1
   ERROR_CODE="$?"
   if [ ${ERROR_CODE} -eq 0 ]
@@ -1994,20 +2140,21 @@ event_bridge_remove_rule()
 
 events_create_cron_rule()
 {
-  if [ $# -ne 2 ]
+  if [ $# -ne 3 ]
   then
-    error "Function ${LIME}${FUNCNAME[0]}${RED} needs two parameter: ${YELLOW}(1)event_rule_name, (2)cron_event_schedule"
+    error "Function ${LIME}${FUNCNAME[0]}${RED} needs three parameters: ${YELLOW}(1)event_rule_name, (2)cron_event_schedule, (3)description_of_rule"
     ERROR_CODE="1"
     failed
   else
     EVENT_BRIDGE_RULE_NAME="${1}"
     EVENT_BRIDGE_RULE_NAME_SCHEDULE="${2}"
+    EVENT_BRIDGE_RULE_DESCRIPTION="${3}"
   fi
   EVENT_BRIDGE_RULE_NAME_CHECK=$(jq -r --arg event_bridge_rule_name ${EVENT_BRIDGE_RULE_NAME} '.Rules[] | select(.Name == $event_bridge_rule_name) | .Arn' "${TMP}/${AWS_EVENTS_RULES}_full.json")
   if [ -z ${EVENT_BRIDGE_RULE_NAME_CHECK} ]
   then
     inf "    Adding event rule: ${LIME}${EVENT_BRIDGE_RULE_NAME}${CYAN} with schedule: ${BROWN}\"${EVENT_BRIDGE_RULE_NAME_SCHEDULE}\""
-    aws ${AWS_PROFILE_USE_CHECK[*]} events put-rule --schedule-expression "${EVENT_BRIDGE_RULE_NAME_SCHEDULE}" --name ${EVENT_BRIDGE_RULE_NAME} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}_full.json" 2>"${LOG}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}.log"
+    aws ${AWS_PROFILE_USE_CHECK[*]} events put-rule --schedule-expression "${EVENT_BRIDGE_RULE_NAME_SCHEDULE}" --name ${EVENT_BRIDGE_RULE_NAME} --description "${EVENT_BRIDGE_RULE_DESCRIPTION}" > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}_full.json" 2>"${LOG}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}.log"
     ERROR_CODE="$?"
     if [ ${ERROR_CODE} -eq 0 ]
     then
@@ -2119,7 +2266,7 @@ lambda_get_policy()
     error "      Appropriate permissions and trust to: ${DARK_GREEN}${EVENT_BRIDGE_EVENT_NAME}${RED} are NOT set"
     if [ ! -s "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE_NAME}_full.json" ]
     then
-      events_create_cron_rule ${EVENT_BRIDGE_RULE_NAME} "${EVENT_SCHEDULE}"
+      events_create_cron_rule ${EVENT_BRIDGE_RULE_NAME} "${EVENT_SCHEDULE}" "event rule related to: ${AWS_LAMBDA_FUNCTION_NAME}"
       events_list_of_rules
     fi
     lambda_add_permission_to_trust_principal ${AWS_LAMBDA_FUNCTION_NAME} ${EVENT_BRIDGE_EVENT_NAME} events.amazonaws.com ${EVENT_BRIDGE_RULE_NAME}
