* added checking of S3 buckets features like secure access instead of apply it each time
* Lambda and Evens are now taken from one filke, with schedule, so it shhould be easier then it was

diff --git a/config_aws b/config_aws
--- a/config_aws
+++ b/config_aws
@@ -1372,24 +1372,23 @@ aws_S3_bucket_encryption()
   else
     S3_BUCKET_NAME="${1}"
   fi
-  inf "      checking encryption of a bucket ${YELLOW}${S3_BUCKET_NAME}${CYAN}:"
-  aws s3api get-bucket-encryption --bucket ${S3_BUCKET_NAME} ${AWS_PROFILE_USE_CHECK} > "${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_encryption.json" 2>&1
+  aws ${AWS_PROFILE_USE_CHECK} s3api get-bucket-encryption --bucket ${S3_BUCKET_NAME} > "${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_encryption.json" 2>&1
   ERROR_CODE="$?"
   if [ ${ERROR_CODE} -ne 0 ]
   then
-    inf "        S3 bucket: ${YELLOW}${S3_BUCKET_NAME}${CYAN} was created without encryption, setting it now..."
+    inf "      S3 bucket (${YELLOW}${S3_BUCKET_NAME}${CYAN}) was created without ${DARK_GREEN}encryption${CYAN}, setting it now..."
     aws s3api put-bucket-encryption --bucket ${S3_BUCKET_NAME} --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}' ${AWS_PROFILE_USE_CHECK}
     ERROR_CODE="$?"
     if [ ${ERROR_CODE} -ne 0 ]
     then
-      error "          encryption on S3 bucket ${YELLOW}${S3_BUCKET_NAME}${RED} failed"
-      debug "            LOG FILE: ${YELLOW}${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_encryption.log"
+      error "        Encryption on S3 bucket (${YELLOW}${S3_BUCKET_NAME}${RED}) failed"
+      debug "          LOG FILE: ${YELLOW}${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_encryption.log"
       failed
     else
-      inf "          encryption on S3 bucket: ${YELLOW}${S3_BUCKET_NAME}${CYAN} applied properly"
+      inf "        Encryption on S3 bucket (${YELLOW}${S3_BUCKET_NAME}${CYAN}) applied properly"
     fi
   else
-    inf "        S3 bucket: ${YELLOW}${S3_BUCKET_NAME}${CYAN} encryption is already enabled"
+    inf "      S3 bucket (${YELLOW}${S3_BUCKET_NAME}${CYAN}) ${DARK_GREEN}encryption${CYAN} is enabled"
   fi
 }
 
@@ -1403,46 +1402,52 @@ aws_S3_bucket_secure_access_policy()
   else
     S3_BUCKET_NAME="${1}"
   fi
-  inf "      applying bucket policy (${DARK_GREEN}SecureTransport${CYAN}) for ${YELLOW}${S3_BUCKET_NAME}${CYAN}:"
-  echo "      {
-    \"Statement\":
-    [
-      {
-        \"Effect\": \"Allow\",
-        \"Principal\":
+  S3_BUCKET_SECURE_POLICY_CHECK=$(aws ${AWS_PROFILE_USE_CHECK} s3api get-bucket-policy --bucket ${S3_BUCKET_NAME} --output text | jq -r '.Statement[] | select(.Condition.Bool."aws:SecureTransport" == "false") | .Effect')
+  if [[ ${S3_BUCKET_SECURE_POLICY_CHECK} == "Deny" ]]
+  then
+    inf "    S3 bucket (${YELLOW}${S3_BUCKET_NAME}${CYAN}) policy (${DARK_GREEN}SecureTransport${CYAN}) is applied"
+  else
+    inf "    Applying bucket (${YELLOW}${S3_BUCKET_NAME}${CYAN}) policy (${DARK_GREEN}SecureTransport${CYAN}) for ${YELLOW}${S3_BUCKET_NAME}${CYAN}:"
+    echo "      {
+      \"Statement\":
+      [
         {
-          \"AWS\":
-          [
-            \"${AWS_OWNER_ID}\"
-          ]
-        },
-        \"Action\": \"s3:*\",
-        \"Resource\": \"arn:aws:s3:::${S3_BUCKET_NAME}/*\"
-      },
-      {
-        \"Effect\": \"Deny\",
-        \"Principal\": \"*\",
-        \"Action\": \"*\",
-        \"Resource\": \"arn:aws:s3:::${S3_BUCKET_NAME}/*\",
-        \"Condition\":
-        {
-          \"Bool\":
+          \"Effect\": \"Allow\",
+          \"Principal\":
           {
-            \"aws:SecureTransport\": \"false\"
+            \"AWS\":
+            [
+              \"${AWS_OWNER_ID}\"
+            ]
+          },
+          \"Action\": \"s3:*\",
+          \"Resource\": \"arn:aws:s3:::${S3_BUCKET_NAME}/*\"
+        },
+        {
+          \"Effect\": \"Deny\",
+          \"Principal\": \"*\",
+          \"Action\": \"*\",
+          \"Resource\": \"arn:aws:s3:::${S3_BUCKET_NAME}/*\",
+          \"Condition\":
+          {
+            \"Bool\":
+            {
+              \"aws:SecureTransport\": \"false\"
+            }
           }
         }
-      }
-    ]
-  }" | sed 's/^      //g' > "${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.json"
-  aws s3api put-bucket-policy --bucket ${S3_BUCKET_NAME} --policy file://"${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.json" ${AWS_PROFILE_USE_CHECK} > "${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.log" 2>&1
-  ERROR_CODE="$?"
-  if [ ${ERROR_CODE} -eq 0 ]
-  then
-    inf "        S3 bucket policy has just been applied"
-  else
-    error "        S3 bucket policy applying failed"
-    debug "          LOG FILE: ${YELLOW}${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.log"
-    failed
+      ]
+    }" > "${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.json"
+    aws ${AWS_PROFILE_USE_CHECK} s3api put-bucket-policy --bucket ${S3_BUCKET_NAME} --policy file://"${TMP}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.json" > "${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.log" 2>&1
+    ERROR_CODE="$?"
+    if [ ${ERROR_CODE} -eq 0 ]
+    then
+      inf "      S3 bucket policy has just been applied"
+    else
+      error "      S3 bucket policy applying failed"
+      debug "        LOG FILE: ${YELLOW}${LOG}/${AWS_S3BUCKETS_DETAILS}_${S3_BUCKET_NAME}_bucket_policy.log"
+      failed
+    fi
   fi
 }
 
@@ -1481,13 +1486,6 @@ if [ $# -ne 1 ]
     SECURITY_GROUP_ID="${1}"
   fi
   inf "    Deleting security group ${YELLOW}${SECURITY_GROUP_ID}"
-  #ToDo: if security group is still attached to termianted instance, first it must be detached:
-  #aws --profile ${AWS_PROFILE} ec2 describe-network-interfaces --filters Name=group-id,Values=${SECURITY_GROUP_ID} | jq -r '.NetworkInterfaces[].Attachment.InstanceId'
-  #(jq -r --arg aws_instance_id ${AWS_INSTANCE_ID} '.Reservations[].Instances[] | select(.InstanceId == $aws_instance_id) | .State.Name' "${TMP}/${AWS_INSTANCES_DETAILS}_full.json"
-  #there is no chance during termination to neither detach od relete interface, so there is no chance to remove security group
-  #or maybe NOT delete security group when instance is in a state: terminated
-  #DeleteOnTermination "true"
-  #Status "attached"
   if [[ ${AWS_ZONE} == "Y" ]]
   then
     aws ec2 describe-network-interfaces --filters Name=group-id,Values=${SECURITY_GROUP_ID} > "${TMP}/${AWS_SECURITY_GROUPS}_network_interface_${SECURITY_GROUP_ID}_full.json" 2>&1 
@@ -1550,26 +1548,65 @@ aws_security_group_ingress_add()
   fi
 }
 
-#  if [ ! -z ${EXTERNAL_INET_IP} ]
-#  then
-#    if [[ ${EXTERNAL_INET_IP} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
-#    then
-#      inf "      Adding external/public IP address: ${LIME}${EXTERNAL_INET_IP}${CYAN} to allow ssh to instance(s)"
-#      aws ec2 ${AWS_PROFILE_USE_CHECK} authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 22 --cidr ${EXTERNAL_INET_IP}/32 >> "${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_ingress_public.json"  2>&1
-#      ERROR_CODE="$?"
-#      if [ ${ERROR_CODE} -eq 0 ]
-#      then
-#        inf "        Adding external/public IP address: ${LIME}${EXTERNAL_INET_IP}${CYAN} succedeed"
-#        aws ec2 ${AWS_PROFILE_USE_CHECK} describe-security-groups > "${TMP}/${AWS_SECURITY_GROUPS}_full.json" 2>&1
-#      else
-#        error "        Adding external/public IP address: ${LIME}${EXTERNAL_INET_IP}${RED} failed, exiting"
-#        debug "          LOG FILE: ${YELLOW}${TMP}/${AWS_SECURITY_GROUPS}_${SECURITY_GROUP_ID}_ingress_public.json"
-#        failed
-#      fi
-#    fi
-#  fi
-#}
+events_remove_target()
+{
+  if [ $# -ne 2 ]
+  then
+    error "Function ${LIME}${FUNCNAME[0]}${RED} needs two parameter: ${YELLOW}(1)event_target_Id, (2)event_rule_name"
+    ERROR_CODE="1"
+    failed
+  else
+    EVENT_TARGET_ID="${1}"
+    EVENT_TARGET_NAME=$(echo "${EVENT_TARGET_ID}" | awk -F\: '{print $NF}')
+    EVENT_RULE_NAME="${2}"
+  fi
+  inf "      Target: ${GREEN}${EVENT_TARGET_ID}${CYAN} will be removed from rule:  ${LIME}${EVENT_RULE_NAME}"
+  if [[ ${AWS_ZONE} == "Y" ]]
+  then
+    aws events remove-targets --rule ${EVENT_RULE} --ids ${EVENT_TARGET_ID} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_TARGET_NAME}_target_full.json" 2>&1
+  elif [[ ${AWS_ZONE} == "N" ]]
+  then
+    aws --profile ${AWS_PROFILE} events remove-targets --rule ${EVENT_RULE} --ids ${EVENT_TARGET_ID} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_TARGET_NAME}_target_full.json" 2>&1
+  fi
+  ERROR_CODE="$?"
+  if [ ${ERROR_CODE} -eq 0 ]
+  then
+    inf "        Target: ${GREEN}${EVENT_TARGET_ID}${CYAN} removed properly"
+  else
+    error "        Target: ${GREEN}${EVENT_TARGET_ID}${RED} wasn't removed properly"
+    debug "          LOG FILE: ${YELLOW}${TMP}/${AWS_EVENTS_RULES}_${EVENT_TARGET_NAME}_target_full.json"
+    failed
+  fi
+}
 
+events_remove_rule()
+{
+  if [ $# -ne 1 ]
+  then
+    error "Function ${LIME}${FUNCNAME[0]}${RED} needs two parameter: ${YELLOW}(1)event_rule_name"
+    ERROR_CODE="1"
+    failed
+  else
+    EVENT_RULE_NAME="${1}"
+  fi
+  inf "      Removing rule: ${LIME}${EVENT_RULE_NAME}"
+  if [[ ${AWS_ZONE} == "Y" ]]
+  then
+    aws events delete-rule --name ${EVENT_RULE_NAME} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_RULE_NAME}_full.json" 2>&1
+  elif [[ ${AWS_ZONE} == "N" ]]
+  then
+    aws --profile ${AWS_PROFILE} events delete-rule --name ${EVENT_RULE_NAME} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_RULE_NAME}_full.json" 2>&1
+  fi
+  ERROR_CODE="$?"
+  if [ ${ERROR_CODE} -eq 0 ]
+  then
+    inf "        Rule: ${LIME}${EVENT_RULE_NAME}${CYAN} removed properly"
+  else
+    error "        Rule: ${LIME}${EVENT_RULE_NAME}${RED} wasn't removed properly"
+    debug "          LOG FILE: ${YELLOW}${TMP}/${AWS_EVENTS_RULES}_${EVENT_RULE_NAME}_full.json"
+    failed
+  fi
+}
 aws_run_EC2_code()
 {
   if [ $# -ne 4 ]
diff --git a/deploy_lambda b/deploy_lambda
--- a/deploy_lambda
+++ b/deploy_lambda
@@ -88,18 +88,18 @@ DEPLOY_TIME=$(echo "scale=4; x=(${END_DEPLOY_TIME} - ${START_DEPLOY_TIME}); if(x
 
 START_DEPLOY_LAMBDA_TIME=$(date +%s.%4N)
 #AWS Lambda deployment
-
+#ToDo: prepare the whole package for python things
 if [ -s "${TMP}/${AWS_ROLES}_${AWS_EC2_LAMBDA_ROLE}_creation.json" ]
 then
   export EC2_LAMBDA_ROLE_ARN=$(jq -r '.Role.Arn' "${TMP}/${AWS_ROLES}_${AWS_EC2_LAMBDA_ROLE}_creation.json")
 fi
-
-AWS_LAMBDA_SCRIPT_NAMES=($(awk -F\~ '{print $1}' ${SCRIPTS_HOME}/lambda_functions/lambda_events.config))
+AWS_LAMBDA_SCRIPT_NAMES=($(awk -F\~ '{print $1}' "${SCRIPTS_HOME}/lambda_functions/lambda_events.config"))
 for LAMBDA_SCRIPT in ${AWS_LAMBDA_SCRIPT_NAMES[*]}
 do
   AWS_LAMBDA_NAME="${AWS_COMMON_NAME}_$(echo ${LAMBDA_SCRIPT} | awk -F\. '{print $1}')_lambda"
   AWS_HANDLER_FUNCTION_NAME="$(echo ${LAMBDA_SCRIPT} | awk -F\. '{print $1}')_handler"
   AWS_LAMBDA_HANDLER="${AWS_LAMBDA_NAME}.${AWS_HANDLER_FUNCTION_NAME}"
+  export SHELL_SCRIPT="$(echo "$(cat ${SCRIPTS_HOME}/lambda_functions/$(echo ${LAMBDA_SCRIPT} | awk -F\. '{print $1}').bash)")"
   export KEY_NAME
   export AWS_EC2_INSTANCES_PROFILE
   export AWS_HANDLER_FUNCTION_NAME
@@ -109,48 +109,45 @@ do
   export REGION
   export SECURITY_GROUP_ID
   lambda_function_deployment ${AWS_LAMBDA_NAME} ${AWS_HANDLER_FUNCTION_NAME} 
+  debug "  Lambda EventBridge schedule deployment"
+  IFS=$'\n'
+  for EVENT_SCHEDULE in $(grep ${LAMBDA_SCRIPT} "${SCRIPTS_HOME}/lambda_functions/lambda_events.config" | awk -F\~ '{print $2}')
+  do
+    echo "EVENT_SCHEDULE=${EVENT_SCHEDULE}"
+    #AWS events
+    EVENT_BRIDGE_RULE="${AWS_LAMBDA_NAME}_rule"
+    #debug "    Creating EventBus (it doesn't support cron jobs)"
+    #aws ${AWS_PROFILE_USE_CHECK} events create-event-bus --name ${AWS_COMMON_NAME}-EC2_scripts_deployment_bus > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_BUS}_full.json" 2>&1
+    debug "    Putting rule: ${EVENT_BRIDGE_RULE} with cron: \"${EVENT_SCHEDULE}\""
+    aws --profile ${AWS_PROFILE} events put-rule --schedule-expression "cron${EVENT_SCHEDULE}" --name ${EVENT_BRIDGE_RULE} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE}_full.json" 2>&1
+    ERROR_CODE="$?"
+    warn "error: ${ERROR_CODE}"
+    debug "      Putting target: \"Id\"=\"1\",\"Arn\"=\"${EC2_LAMBDA_SCRIPT_ARN}\" to the rule: ${AWS_COMMON_NAME}-${AWS_LAMBDA_NAME}_invoke_rule"
+    aws --profile ${AWS_PROFILE} events put-targets --rule ${EVENT_BRIDGE_RULE} --targets "Id"="1","Arn"="${EC2_LAMBDA_SCRIPT_ARN}" > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE}_target1_full.json" 2>&1
+    ERROR_CODE="$?"
+    warn "error: ${ERROR_CODE}"
+    #AWS events
+  done
 
-########################
-##Only for current tests - will be removed soon when lambda script will work as expected
-##AWS Lambda invoking
-  inf "invoking lambda function ${YELLOW}${AWS_LAMBDA_NAME}${RED} (when event bridge will be configured properly this will be removed)"
-  #logs from CloudWatch
-  #aws ${AWS_PROFILE_USE_CHECK} logs get-log-events --log-group-name /aws/lambda/${AWS_LAMBDA_NAME} --log-stream-name $(cat out) --limit 5
-  aws ${AWS_PROFILE_USE_CHECK} lambda invoke --function-name ${AWS_LAMBDA_NAME} "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}_full.json" --log-type Tail --query 'LogResult' --output text |  base64 -d > "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}.log" 2>&1
-  ERROR_CODE="$?"
-  INSTANCE_ID_LAMBDA=$(grep "^i-" "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}.log")
-  aws ${AWS_PROFILE_USE_CHECK} ec2 describe-instances --instance-ids ${INSTANCE_ID_LAMBDA} > "${TMP}/${AWS_INSTANCES_DETAILS}_full.json" 2>&1
-  AWS_INSTANCE_DETAILS_IP=$(jq -r '.Reservations[].Instances[].PrivateIpAddress' "${TMP}/${AWS_INSTANCES_DETAILS}_full.json")
-  if [ -z ${AWS_INSTANCE_DETAILS_IP} ] || [[ ${AWS_INSTANCE_DETAILS_IP} =~ null ]]
+  if [[ ${RUN_SCRIPT} == yes ]]
   then
-    error "  Instance hasn't been run, exiting"
-    failed
-  fi
-  inf "  Instance: ${YELLOW}${INSTANCE_ID_LAMBDA}${CYAN} with IP: ${LIME}${AWS_INSTANCE_DETAILS_IP}${CYAN} has just been created"
-  is_instance_up ${INSTANCE_ID_LAMBDA}
-##AWS Lambda invoking
-##Only for current tests - will be removed soon when lambda script will work as expected
-########################
-
-  #AWS events
-  EVENT_BRIDGE_BUS="${AWS_LAMBDA_NAME}_bus"
-  EVENT_BRIDGE_RULE="${AWS_LAMBDA_NAME}_lambda"
-  debug "EventBridge deployment"
-  debug "  creating EventBus"
-  # - it doesn;t support cron - named bus: 
-  aws ${AWS_PROFILE_USE_CHECK} events create-event-bus --name ${EVENT_BRIDGE_RULE} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_BUS}_full.json" 2>&1
-  # - it doesn;t support cron:
-  debug "EventBridge deployment"
-  debug "  putting rule: ${EVENT_BRIDGE_RULE} with cron: (0 8 ? * MON-FRI *)"
-  aws ${AWS_PROFILE_USE_CHECK} events put-rule --schedule-expression "cron(0 8 ? * MON-FRI *)" --name ${EVENT_BRIDGE_RULE} > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE}_full.json" 2>&1 
-  ERROR_CODE="$?"
-  warn "error: ${ERROR_CODE}"
-  debug "    putting target: \"Id\"=\"1\",\"Arn\"=\"${EC2_LAMBDA_SCRIPT_ARN}\" to the rule: ${AWS_COMMON_NAME}-${AWS_LAMBDA_NAME}_invoke_rule"
-  aws --profile ${AWS_PROFILE} events put-targets --rule ${EVENT_BRIDGE_RULE} --targets "Id"="1","Arn"="${EC2_LAMBDA_SCRIPT_ARN}" > "${TMP}/${AWS_EVENTS_RULES}_${EVENT_BRIDGE_RULE}_target1_full.json" 2>&1
-  ERROR_CODE="$?"
-  warn "error: ${ERROR_CODE}"
-  #AWS events
-  #ToDo: prepare the whole package for python things
+    inf "  Invoking lambda function ${YELLOW}${AWS_LAMBDA_NAME}${RED} (when event bridge will be configured properly this will be removed)"
+    #logs from CloudWatch
+    #aws ${AWS_PROFILE_USE_CHECK} logs get-log-events --log-group-name /aws/lambda/${AWS_LAMBDA_NAME} --log-stream-name $(cat out) --limit 5
+    aws ${AWS_PROFILE_USE_CHECK} lambda invoke --function-name ${AWS_LAMBDA_NAME} "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}_full.json" --log-type Tail --query 'LogResult' --output text |  base64 -d > "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}.log" 2>&1
+    ERROR_CODE="$?"
+    INSTANCE_ID_LAMBDA=$(grep "^i-" "${LOG}/${AWS_LAMBDA_FUNCTIONS}_${AWS_LAMBDA_NAME}.log")
+    aws ${AWS_PROFILE_USE_CHECK} ec2 describe-instances --instance-ids ${INSTANCE_ID_LAMBDA} > "${TMP}/${AWS_INSTANCES_DETAILS}_full.json" 2>&1
+    AWS_INSTANCE_DETAILS_IP=$(jq -r '.Reservations[].Instances[].PrivateIpAddress' "${TMP}/${AWS_INSTANCES_DETAILS}_full.json")
+    if [ -z ${AWS_INSTANCE_DETAILS_IP} ] || [[ ${AWS_INSTANCE_DETAILS_IP} =~ null ]]
+    then
+      error "    Instance hasn't been run, exiting"
+      failed
+    fi
+    inf "    Instance: ${YELLOW}${INSTANCE_ID_LAMBDA}${CYAN} with IP: ${LIME}${AWS_INSTANCE_DETAILS_IP}${CYAN} has just been created"
+    is_instance_up ${INSTANCE_ID_LAMBDA}
+    ##AWS Lambda invoking
+    fi
 done
 
 END_DEPLOY_LAMBDA_TIME=$(date +%s.%4N)
